### PR TITLE
usobasicinstallationfileszip_25052448

### PR DESCRIPTION
**Pull request by unreal-archive-submitter**
Add content: 
 - [UT2004 MUTATOR] USOBasicInstallationFiles

---
Submission log: https://unrealarchive.org/submit/#25052448

### CODE REVIEW

**Comment by shrimpza** [comment]
This content is entirely useless on its own. It appears to be somoene's assembled cache dump. There are no int files, not maps, nothing of actual usable value without any context.

**Comment by PootisKorn** [comment]
It's the companion piece for this map:  https://unrealarchive.org/maps/unreal-tournament-2004/onslaught/T/ons-torlan-usoparadise-v1f_ebe02ef6.html

But I suppose without int files it is, indeed, of no use.

**Comment by shrimpza** [comment]
I'm trying to see if there's a way of loading files with no defined content type.

Since the files will still have potential value in that as you say, they're potentially needed by other things.

So I'm keeping this around and leaving it open until I figure that out.

**Comment by shrimpza** [comment]
I've repacked this with the original map which needs it.

**Pull request closed without merging**
