### PR TITLE
accessplus7z

### PR DESCRIPTION
**Pull request by unreal-archive-submitter**
Add content: 
 - [MUTATOR] ClanManager
 - [MUTATOR] Strategic Vehicles
 - [MUTATOR] ReplicationHandler
 - [MUTATOR] UltraRifle
 - [MUTATOR] UAdminMod v0.9.5b BETA 
 - [MUTATOR] PlayerModifer
 - [MUTATOR] ReplicationHandler
 - [MUTATOR] PortalGun
 - [MAP_PACK] Maps
 - [MUTATOR] Vehicle Detonators
 - [MUTATOR] Dual OMFG Gun Arena
 - [MUTATOR] Multi Dodging 2k4 v3
 - [MUTATOR] TranSpider
 - [MAP] AS-Sett-Imploder
 - [MUTATOR] DruidsRPG
 - [MUTATOR] EZVote
 - [MUTATOR] Pillar Gun Mutator
 - [MUTATOR] Cache Extractor
 - [MUTATOR] AccessMut
 - [MUTATOR] UT2004 RPG
 - [MUTATOR] Ripjack Replacer
 - [MUTATOR] OMFG Gun Arena
 - [MUTATOR] HL2Monsters
 - [MUTATOR] UT2Vote57
 - [MUTATOR] AdminPlus_v14
 - [MUTATOR] mass vacuum

### CODE REVIEW

**Comment by shadoskill** [comment]
Hey I just submitted this and a few things it skipped over it claimed couldn't not find any content.
Such as the constructor gun, mover rifle and a few other that I couldn't find anywhere else that I had saved from back in the day.

**Comment by shrimpza** [comment]
Cool, thanks.

For the other files - if you could put them on google drive or something for me to download, I can manually add them if needed, just put the links here and I'll grab them :+1:

**Comment by shadoskill** [comment]
These are the ones it skipped over.
https://drive.google.com/drive/folders/1ohPoxNAtuSoZP3gGv7VqHOJ9RHBhfg1j?usp=sharing

**Comment by shrimpza** [comment]
> These are the ones it skipped over.
> https://drive.google.com/drive/folders/1ohPoxNAtuSoZP3gGv7VqHOJ9RHBhfg1j?usp=sharing

Thanks. I have uploaded the maps separately, and will grab and inspect the other things to see why they aren't being detected.

**Pull request merged**
