### PR TITLE
Update URLs and add missing content

### PR DESCRIPTION
**Pull request by vohzd**
Hello,

I've added some content that's been added since I last mirrored this. I've also updated the URLs too.

Please find all the updated links. I've tested each one with a script and can confirm they're downloadable.

Thanks,

### CODE REVIEW

**Comment by shrimpza** [comment]
Thanks!

The downloads seem to be redirecting to some sort of HTML console page ("MinIO Console"); so although the files are downloaded to the client as .zip files, they're all around 1.2kb, and aren't actually valid zips.

In some places some character encodings were changed too, rendering the YAML files unparsable by the Unreal Archive tool itself - seems it replaced the escaped representations of some exotic single quotes from `\x91` and `\x92` with the literal representations.

I can fix the encoding issue, but the bigger problem seems to be the missing files.

Here's an example: 

https://files.vohzd.com/unreal/unreal-tournament-3/maps/death-match/DM-Pinnicale.zip

Is it maybe a bucket permissions problem, or something like that?

**Comment by vohzd** [comment]
Whoops! Yes thank you for catching that... I hadn't made the bucket public (readonly) and I'd messed up the DNS records!

I've just corrected that now and can confirm I'm getting the actual file (Pinnicale now is ~100meg instead of 1.2kb)

Regarding the encoding issue, over Christmas I wrote a (janky) indexer in Node as a learning project, so I've used a [lib ](https://www.npmjs.com/package/yaml) to convert back and forth from JSON<->YAML which has probably caused the encoding issue.

https://github.com/vohzd/unreal-mirror/blob/main/src/utils/convertYamlToJson.ts

I'm happy to fix this from my side? Or if you think it's a quick fix happy to leave with you.

Thanks again for all your work on this.

**Comment by shrimpza** [comment]
Great, thanks :). 

I'd already done the encoding fix (I like to run the tool via the `./unreal-archive summary` command to ensure a big change like this still yields the proper results), so I just pushed that via a commit.

Here goes the merge :crossed_fingers:

**Comment by shrimpza** [comment]
Looks like it's all good.

Thanks for the updated mirror!

**Comment by vohzd** [comment]
Amazing! Thank you very much for all that!

**Pull request merged**
